config/routes.rb
Rails.application.routes.draw do
  resources :finances
  devise_for :users
    
  resources :pastures
  resources :herds
  resources :animals
  root 'welcome#index'
  resources :livestock
  
  #resources :users, only: [:show]
  get 'dashboard_select', to: 'herds#dashboard_select'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/finance.rb
class Finance < ApplicationRecord
  belongs_to :user
  has_one :herd
  has_many :animals, through: :herd
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = current_user.finances
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = current_user.finances.build
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = current_user.finances.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:item, :category, :amount, :pay_type, :tran_type, :herd_id)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_form.html.erb
<%= form_with(model: finance, local: true) do |form| %>
  <% if finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
<%= form.label "Select Animal Group" %>   
<%= form.collection_select(:herd_id, current_user.herds, :id, :name, {prompt: "Enter a Herd"}, {class: "w3-select"}) %>  <%#= Herd.find(@animal.herd_id).name %>
</div>
  
  <div class="field">
    <%#= form.label :herd_id %>
    <%#= form.text_field :herd_id %>
  </div>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :pay_type %>
    <%= form.select :pay_type, ['CC', 'Check', 'Cash']%>
  </div>

  <div class="field">
    <%= form.label :tran_type %>
    <%= form.select :tran_type, ['Income', 'Expense']%>
      
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form', finance: @finance %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Finances</h1>
<table class="table-hover table-striped table-bordered" cellpadding="10">
  
 

  <thead>
    <tr>
      <th>Herd</th>
      <th>Item</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Pay type</th>
      <th>Tran type</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
    <% if finance.herd_id = 1 %> 
      <tr>
        <% if finance.herd_id %>
        <td><%= Herd.find(finance.herd_id).name %></td>
        <% else %>
        <td class="danger">No Herd</td>
        <% end %>
        <td><%= finance.item %></td>
        <td><%= finance.category %></td>
        <% if finance.tran_type == "Expense" %>
        <td class="color:red;"><%= -finance.amount %></td>
        <% else %>
        <td><%= finance.amount %></td>
        <% end %>
        
        <td><%= finance.pay_type %></td>
        <td><%= finance.tran_type %></td>
        
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
    <% @total = 0 %>
    <% @finances.each do |finance| %>
    <% if finance.tran_type == "Expense" %>
    <% @total = @total - finance.amount %>
    <% else %>
    <% @total = @total + finance.amount %>
    <% end %>
    <% end %>
    <tr>
      <th>Total</th>
      <td></td>
      <td><%= @total %></td>
    </tr>
   
  </tbody>
</table>

<br>


<%= link_to 'New Finance', new_finance_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form', finance: @finance %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Herd:</strong>
  <%= Herd.find(@finance.herd_id).name %>
</p>


<p>
  <strong>Item:</strong>
  <%= @finance.item %>
</p>

<p>
  <strong>Category:</strong>
  <%= @finance.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @finance.amount %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @finance.pay_type %>
</p>

<p>
  <strong>Tran type:</strong>
  <%= @finance.tran_type %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>