config/routes.rb
Rails.application.routes.draw do
  resources :finances
  devise_for :users
    
  resources :pastures
  resources :herds
  resources :animals
  root 'welcome#index'
  resources :livestock
  
  #resources :users, only: [:show]
  get 'dashboard_select', to: 'herds#dashboard_select'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pasture.rb
class Pasture < ApplicationRecord
  belongs_to :user
  has_one :herd
  has_many :animals, through: :herd
end

app/controllers/pastures_controller.rb
class PasturesController < ApplicationController
  before_action :set_pasture, only: [:show, :edit, :update, :destroy]

  # GET /pastures
  # GET /pastures.json
  def index
    @pastures = current_user.pastures
  end

  # GET /pastures/1
  # GET /pastures/1.json
  def show
  end

  # GET /pastures/new
  def new
    @pasture = current_user.pastures.build
  end

  # GET /pastures/1/edit
  def edit
  end

  # POST /pastures
  # POST /pastures.json
  def create
    @pasture = current_user.pastures.new(pasture_params)

    respond_to do |format|
      if @pasture.save
        format.html { redirect_to @pasture, notice: 'Pasture was successfully created.' }
        format.json { render :show, status: :created, location: @pasture }
      else
        format.html { render :new }
        format.json { render json: @pasture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastures/1
  # PATCH/PUT /pastures/1.json
  def update
    respond_to do |format|
      if @pasture.update(pasture_params)
        format.html { redirect_to @pasture, notice: 'Pasture was successfully updated.' }
        format.json { render :show, status: :ok, location: @pasture }
      else
        format.html { render :edit }
        format.json { render json: @pasture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastures/1
  # DELETE /pastures/1.json
  def destroy
    @pasture.destroy
    respond_to do |format|
      format.html { redirect_to pastures_url, notice: 'Pasture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pasture
      @pasture = Pasture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pasture_params
      params.require(:pasture).permit(:date_grazed, :available_forage, :size, :herd_id)
    end
end

app/helpers/pastures_helper.rb
module PasturesHelper
end

app/views/pastures/_form.html.erb
<%= form_with(model: pasture, local: true) do |form| %>
  <% if pasture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pasture.errors.count, "error") %> prohibited this pasture from being saved:</h2>

      <ul>
      <% pasture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_grazed %>
    <%= form.date_select :date_grazed %>
  </div>

  <div class="field">
    <%= form.label :available_forage %>
    <%= form.number_field :available_forage %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pastures/edit.html.erb
<h1>Editing Pasture</h1>

<%= render 'form', pasture: @pasture %>

<%= link_to 'Show', @pasture %> |
<%= link_to 'Back', pastures_path %>

app/views/pastures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pastures</h1>

<table class="table-hover table-striped table-bordered" cellpadding="10">
  <thead>
    <tr>
      <th>Pasture ID</th>
      <th>Date grazed</th>
      <th>Available forage</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pastures.each do |pasture| %>
      <tr>
        <td><%= pasture.id %></td>
        <td><%= pasture.date_grazed %></td>
        <td><%= pasture.available_forage %></td>
        <td><%= pasture.size %></td>
        <td><%= link_to 'Show', pasture %></td>
        <td><%= link_to 'Edit', edit_pasture_path(pasture) %></td>
        <td><%= link_to 'Destroy', pasture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pasture', new_pasture_path %>

app/views/pastures/new.html.erb
<h1>New Pasture</h1>

<%= render 'form', pasture: @pasture %>

<%= link_to 'Back', pastures_path %>

app/views/pastures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date last grazed:</strong>
  <%= @pasture.date_grazed %>
</p>

<p>
  <strong>Available forage:</strong>
  <%= @pasture.available_forage %> <strong> #'s per acre</strong>
</p>

<p>
  <strong>Size:
  <%= @pasture.size %> Acre</strong>
</p>

<% if @pasture.herd_id %>
  <p>
    <strong>Herd on Pasture:
    <%= @pasture.herd.name %></strong>
  </p>
<% end %>

<table>

<tbody>
   Animals on Pasture
   <th> Tag Number</th> 
   <th> Breed </th>
   <th> Date of Birth </th>
   <% @pasture.animals.each do |f| %>
    <tr>
      
      
      
        <td><%= f.tag_number %></td>
        <td><%= f.breed %></td>
        <td><%= f.dob %></td>
        
        <td><%= link_to 'Show', f %></td>
        <td><%= link_to 'Edit', edit_animal_path(f) %></td>
        <td><%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
   <% end %>
  </tbody>
</table>
  
  <%= link_to 'Edit', edit_pasture_path(@pasture) %> |
<%= link_to 'Back', pastures_path %>