config/routes.rb
Rails.application.routes.draw do
  resources :finances
  devise_for :users
    
  resources :pastures
  resources :herds
  resources :animals
  root 'welcome#index'
  resources :livestock
  
  #resources :users, only: [:show]
  get 'dashboard_select', to: 'herds#dashboard_select'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  #belongs_to :user
  has_one :herd
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  

  # GET /animals
  # GET /animals.json
  def index
    @animals = current_user.animals
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = current_user.animals.build
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = current_user.animals.new(animal_params)
    #@animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:tag_number, :breed, :dob, :color, :date_exposed, :herd_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true, html: {class: "container"}) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%#= @herd.herd_id %>

  <div class="form-group">
    <%= form.label "Tag Number:" %>
    <%= form.number_field :tag_number, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label "Breed:" %>
    <%#= form.text_field :breed, {class: "form-control"} %>
    <%= form.select(:breed, options_for_select([["Select One", ""], "Angus", "Hereford", "Beefmaster"]), {}, {:class => "form-control"}) %>
  </div>

  <div class="form-group">
    <%= form.label "Date of Birth" %>
    <br>
    <%= form.date_select :dob %>
  </div>

  <div class="form-group">
    <%= form.label "Color" %>
   <%= form.select(:color, options_for_select([["Select One", ""], "Black", "Brown", "White", "Red", "Multi-color"]), {}, {:class => "form-control"}) %>
  </div>

  <div class="form-group">
    <%= form.label "Date Exposed" %>
    <br>
    <%= form.date_select :date_exposed %>
  </div>


<%#  if animal.id %> 
<div class="form-group">
  <%= form.label "Select Animal Group:"%>
<%= form.collection_select(:herd_id, current_user.herds, :id, :name, {prompt: "Enter a Herd"}, {class: "w3-select form-control"}) %> 
</div>
<%# end %>
  
  
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>



<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>


<table class="table-hover table-striped table-bordered" cellpadding="10">
  <thead>
    <tr>
      <th>Tag number </th>
      <th>Breed </th>
      <th>Dob </th>
      <th>Color </th>
      <th>Date Exposed </th>
      <th>Herd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
     <tr>
        <td><%= animal.tag_number %></td>
        <td><%= animal.breed %></td>
        <td><%= animal.dob %></td>
        <td><%= animal.color %></td>
        <td><%= animal.date_exposed %></td>
         <%# if animal.herd %>
        <td><%= Herd.find(animal.herd_id).name %></td>
         <%# end %>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1 class="text-center">
<p>New Animal</p>
</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path(user: current_user, tag_number: @animal.tag_number),
                                      class: "btn btn-xs btn-success", method: :post %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Tag number:</strong>
  <%= @animal.tag_number %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @animal.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @animal.dob %>
</p>

<p>
  <strong>Color:</strong>
  <%= @animal.color %>
</p>

<p>
  <strong>Date Exposed:</strong>
  <%= @animal.date_exposed %>
</p>

<p>
  <strong>Herd:</strong>
  <%# if @animal.herd_id != 0 %>
  <%= Herd.find(@animal.herd_id).name %>
  <%# end %>
</p>



<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>