config/routes.rb
Rails.application.routes.draw do
  resources :finances
  devise_for :users
    
  resources :pastures
  resources :herds
  resources :animals
  root 'welcome#index'
  resources :livestock
  
  #resources :users, only: [:show]
  get 'dashboard_select', to: 'herds#dashboard_select'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/herd.rb
class Herd < ApplicationRecord
  belongs_to :user
  has_many :animals
  has_many :finances
  has_one :pasture
end

app/controllers/herds_controller.rb
class HerdsController < ApplicationController
  before_action :set_herd, only: [:show, :edit, :update, :destroy]
  
  
  # GET /herds
  # GET /herds.json
  def index
    @herds = current_user.herds
  end

  # GET /herds/1
  # GET /herds/1.json
  def show
  end
  
  def dashboard_select
     @herd = current_user.herds.build
  end

  # GET /herds/new
  def new
    @herd = current_user.herds.build
  end

  # GET /herds/1/edit
  def edit
  end

  # POST /herds
  # POST /herds.json
  def create
    @herd = current_user.herds.new(herd_params)

    respond_to do |format|
      if @herd.save
        format.html { redirect_to @herd, notice: 'Herd was successfully created.' }
        format.json { render :show, status: :created, location: @herd }
      else
        format.html { render :new }
        format.json { render json: @herd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /herds/1
  # PATCH/PUT /herds/1.json
  def update
    respond_to do |format|
      if @herd.update(herd_params)
        format.html { redirect_to @herd, notice: 'Herd was successfully updated.' }
        format.json { render :show, status: :ok, location: @herd }
      else
        format.html { render :edit }
        format.json { render json: @herd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /herds/1
  # DELETE /herds/1.json
  def destroy
    @herd.destroy
    respond_to do |format|
      format.html { redirect_to herds_url, notice: 'Herd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herd
      @herd = Herd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def herd_params
      params.require(:herd).permit(:name, :desc, :animals, :pasture_id)
    end
end

app/helpers/herds_helper.rb
module HerdsHelper
end

app/views/herds/_dashboard_select.html.erb
<%= form_with(model: herd, local: true) do |form| %>
  <% if herd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(herd.errors.count, "error") %> prohibited this herd from being saved:</h2>

      <ul>
      <% herd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= form.label "Select Animal Group:"%>
  <%= form.collection_select(:herd_id, current_user.herds, :id, :name, {prompt: "Enter a Herd"}, {class: "w3-select form-control"}) %> 
</div>
   
<% end %>   

app/views/herds/_form.html.erb
<%= form_with(model: herd, local: true) do |form| %>
  <% if herd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(herd.errors.count, "error") %> prohibited this herd from being saved:</h2>

      <ul>
      <% herd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<%= form.label "Enter Pasture ID" %>
  <%= form.collection_select(:pasture_id, current_user.pastures, :id, :id, {prompt: "Enter Pasture"}, {class: "w3-select"}) %> 
  
</div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/herds/dashboard_select.html.erb
<h1>Dashboard</h1>

<%= render 'dashboard_select', herd: @herd %>

<%= link_to 'Show', @herd %> |
<%= link_to 'Back', herds_path %>

app/views/herds/edit.html.erb
<h1>Editing Herd</h1>

<%= render 'form', herd: @herd %>

<%= link_to 'Show', @herd %> |
<%= link_to 'Back', herds_path %>

app/views/herds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Herds</h1>

<table class="table-hover table-striped table-bordered" cellpadding="10">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @herds.each do |herd| %>
      <tr>
        <td><%= herd.name %></td>
        <td><%= herd.desc %></td>
        <td><%= link_to 'Show', herd, class: "btn btn-primary btn-rounded animated fadeInDown wow" %></td>
        <td><%= link_to 'Edit', edit_herd_path(herd), class: "btn btn-primary btn-rounded animated fadeInDown wow"  %></td>
        <td><%= link_to 'Destroy', herd, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-rounded animated fadeInDown wow" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div style="text-align: center;">

<%= link_to 'New Herd', new_herd_path, class: "btn btn-primary btn-rounded w-lg animated fadeInDown wow" %>

  
</div>

app/views/herds/new.html.erb
<h1>New Herd</h1>

<%= render 'form', herd: @herd %>

<%= link_to 'Back', herds_path %>

app/views/herds/show.html.erb
<p id="notice"><%= notice %></p>



<h1 class="text-center">
  <strong>Animal Group:</strong>
  <%= @herd.name %>
</h1>

<h2>
  Current Pasture - (<%= @herd.pasture_id %>)
  <%= link_to 'Move Animal Group', edit_herd_path{@herd.pasture_id}, class: "btn btn-primary btn-rounded w-lg animated fadeInDown wow" %>
</h2>
<table class="table-hover table-striped table-bordered" cellpadding="10">
  
 <tbody>
   <h2>
     Animals in Herd
   </h2>
   <h3><%= link_to 'Add', new_animal_path{@herd.herd_id}, class: "btn btn-primary btn-rounded w-lg animated fadeInDown wow" %> </h3>
   <th> Tag Number</th> 
   <th> Breed </th>
   <th> Date of Birth </th>
   <% @herd.animals.each do |f| %>
    <tr>
      
      
      
        <td><%= f.tag_number %></td>
        <td><%= f.breed %></td>
        <td><%= f.dob %></td>
        <td><%= link_to 'Show', f %></td>
        <td><%= link_to 'Edit', edit_animal_path(f) %></td>
        <td><%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
   <% end %>
  
</tbody>
</table>

<h2>Finances<h2>
  
  <h3><%= link_to 'Add', new_finance_path{@herd.herd_id}, class: "btn btn-primary btn-rounded w-lg animated fadeInDown wow" %> </h3>
<table class="table-hover table-striped table-bordered" cellpadding="10">
  
 

  <thead>
    <tr>
      <th>Item</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Pay type</th>
      <th>Tran type</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @herd.finances.each do |finance| %>
    <%# if finance.herd_id = 1 %> 
      <tr>
        <td><%= finance.item %></td>
        <td><%= finance.category %></td>
        <% if finance.tran_type == "Expense" %>
        <td class="color:red;"><%= -finance.amount %></td>
        <% else %>
        <td><%= finance.amount %></td>
        <% end %>
        
        <td><%= finance.pay_type %></td>
        <td><%= finance.tran_type %></td>
        
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
    <% end %>
    <% @total = 0 %>
    <% @herd.finances.each do |finance| %>
    <% if finance.tran_type == "Expense" %>
    <% @total = @total - finance.amount %>
    <% else %>
    <% @total = @total + finance.amount %>
    <% end %>
    <% end %>
    <tr>
      <th>Total</th>
      <td></td>
      <td></td>
      <td><%= @total %></td>
    </tr>
   </tbody>
</table>


<%= link_to 'Edit', edit_herd_path(@herd) %> |
<%= link_to 'Back', herds_path %>
  
  